### ISSUE TITLE
/admin/users/create  code 200 White page

### ISSUE THREAD

**Issue by LunarDevelopment** [miracuthbert/saas-boilerplate#5]
When logged in with a root-admin account and navigate to /admin/users/create via the admin dashboard it returns a 200 http code but a blank page. 

Fresh install on master branch.

**Comment by miracuthbert** [comment]
I haven't implemented any view for the user routes (except Index) in the Admin **UserController**, since most of the projects I work vary when adding users from the Admin.

So basically just return a _blade_ view in the `create` method of the controller.

**Suggestion:** Based on the projects I work on, basically creating users from the Admin panel involves sending an email invitation with custom invitation types such as: basic signup, admin (with specified role) which are stored in an _invitations_ table; where they can be rejected or accepted by the user.

When I find a better way to implement adding user's from the Admin which can be easily extended, I may add this feature.

If you have a better solution I'd like to hear it.
